name: Kafka CLuster
on: [workflow_dispatch]
jobs:
   APPLY-CHANGES:
    runs-on: self-hosted
    steps:
      - name: Get GitHub Runner IP
        run: curl ifconfig.me

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init -backend-config=environments/dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=environments/dev/state.tfvars -auto-approve