name: Kafka CLuster
on: [workflow_dispatch]
jobs:
   APPLY-CHANGES:
    runs-on: self-hosted
    steps:
      - name: Get GitHub Runner IP
        run: curl ifconfig.me

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make Ansible script executable
        run: chmod +x ./run-ansible.sh

      - name: print ls
        run: ls -al
      - name: Show working directory
        run: pwd && ls -l && ls -R terraform/

      - name: Terraform Init
        run: terraform init -backend-config=environments/dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=environments/dev/state.tfvars -auto-approve

      - name: Print Terraform Outputs (for debug)
        run: terraform output -json