name: Kafka CLuster
on: [workflow_dispatch]
jobs:
   APPLY-CHANGES:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Init
        run: terraform init -backend-config=environments/dev/state.tfvars
      - name: Terraform Apply
        run: terraform apply -var-file=environments/dev/main.tfvars -auto-approve -var vault_token=${{ secrets.VAULT_TOKEN }}